apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra.fullname" . }}
  labels:
    {{- include "cassandra.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: cql
      port: {{ .Values.service.port }}
      targetPort: 9042
  selector:
    app.kubernetes.io/name: {{ include "cassandra.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
