apiVersion: v1
kind: Secret
metadata:
  name: pg-superuser
  namespace: {{ .Values.cluster.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: superuser-password

---
apiVersion: v1
kind: Secret
metadata:
  name: pg-app-user
  namespace: {{ .Values.cluster.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: app_user
  password: app-user-password

