replicaCount: 3

image:
  repository: cassandra
  tag: "4.1"
  pullPolicy: IfNotPresent

resources: {}

service:
  type: ClusterIP
  port: 9042

storage:
  enabled: true
  size: 1Gi
  className: longhorn

config:
  clusterName: "CassandraCluster"
  numTokens: 256

secret:
  username: cassandra
  password: cassandra

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: cassandra.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

httpRoute:
  enabled: false
